import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Test Front-end Eigen",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<AntdRegistry>{children}</AntdRegistry>
			</body>
		</html>
	);
}
